### ISSUE TITLE
common memes turns to undefined

### ISSUE THREAD

**Issue by The-Quill** [ismael-miguel/memer#16]
Typing `Jon Skeet` into the script turns the phrase into `undefined`.

**Comment by malachi26** [comment]
so does Ponies

**Comment by The-Quill** [comment]
It seems to be all the `_common.json` memes

**Comment by malachi26** [comment]
added an else statement to `if (typeof meta !== "undefined)` so that the code would run if there was no site attached to the json file.

This Fixed the issue
